work_dir:  ./work_dir/train_pmnet/
phase: train
alpha: 100.0                      # 100 in paper for eular angle constraint
gamma: 10.0                       # 10 in paper for twist loss
theta: 20.0                       # 20 in paper for reconstruction loss
omega: 0.0                        # 0 in paper for smooth loss
kp: 0.8
margin: 0.3                       # 0.3 in official impl.
balancing: 2                      # 2 in official impl.
euler_ord: yzx
max_length: 60
num_joint: 22

train_feeder_args:
  data_path:  ./datasets/mixamo/train_q
  stats_path:  ./datasets/mixamo/stats
  max_length: 60

ret_model_args:
  num_joint: 22
  hidden_channels_p: 512
  embed_channels_p: 16
  hidden_channels_m: 128
  kp: 0.8

dis_model_args:
  kp: 0.8

epoch: 300
device: [0]
step: [200]
base_lr: 0.0001                # 0.0001 in official impl.
batch_size: 16
weight_decay: 0.0              # 0.0001